name: Release

on: workflow_dispatch

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      attestations: write
      contents: read
      id-token: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up MATLAB
      run: echo 'no-op'
    - name: Build package
      run: echo 'package' > package.txt
    - name: Generate attestation
      uses: actions/attest@v1
      with:
        subject-path: '${{ github.workspace }}/package.txt'
        predicate-type: 'https://example.com/predicate/v1'
        predicate: '{}'
        show-summary: true
